// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WolflineSquadTTT;

#nullable disable

namespace WolflineSquadTTT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203220616_03022026")]
    partial class _03022026
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WolflineSquadTTT.Models.Poll", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PollType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID");

                    b.ToTable("Poll");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.PollOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OptionDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PollFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PollFK");

                    b.ToTable("PollOption");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.UserRight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Right")
                        .HasColumnType("int");

                    b.Property<int>("UserFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserFK");

                    b.ToTable("UserRight");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.Poll", b =>
                {
                    b.OwnsOne("PollReward", "Reward", b1 =>
                        {
                            b1.Property<int>("PollID")
                                .HasColumnType("int");

                            b1.Property<int>("RewardAmount")
                                .HasColumnType("int");

                            b1.Property<string>("RewardType")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("PollID");

                            b1.ToTable("Poll");

                            b1.WithOwner()
                                .HasForeignKey("PollID");
                        });

                    b.Navigation("Reward")
                        .IsRequired();
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.PollOption", b =>
                {
                    b.HasOne("WolflineSquadTTT.Models.Poll", "Poll")
                        .WithMany()
                        .HasForeignKey("PollFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.UserRight", b =>
                {
                    b.HasOne("WolflineSquadTTT.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
