// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WolflineSquadTTT;

#nullable disable

namespace WolflineSquadTTT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626083616_AutoMigration_20260626103611")]
    partial class AutoMigration_20260626103611
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WolflineSquadTTT.Models.MarketListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CurrentBid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HighestBidderSteamId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ItemPersistenceId")
                        .HasColumnType("int");

                    b.Property<int>("KinvItemId")
                        .HasColumnType("int");

                    b.Property<int>("ListingType")
                        .HasColumnType("int");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("SellerSteamId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("SoldAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("SoldPrice")
                        .HasColumnType("bigint");

                    b.Property<string>("SoldToSteamId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SellerSteamId");

                    b.HasIndex("Status");

                    b.ToTable("MarketListing");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.PointShopTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("PointShopTransaction");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.Poll", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("AllowUserInput")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RewardFK")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("RewardFK");

                    b.ToTable("Poll");

                    b.HasDiscriminator().HasValue("Poll");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.PollOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsUserInput")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OptionDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PollFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PollFK");

                    b.ToTable("PollOption");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NormalPoints")
                        .HasColumnType("int");

                    b.Property<int>("PremiumPoints")
                        .HasColumnType("int");

                    b.Property<int>("RewardType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reward");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.RewardClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Claimed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PollFK")
                        .HasColumnType("int");

                    b.Property<int>("RewardFK")
                        .HasColumnType("int");

                    b.Property<int>("UserFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PollFK");

                    b.HasIndex("RewardFK");

                    b.HasIndex("UserFK", "PollFK")
                        .IsUnique();

                    b.ToTable("RewardClaim");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.UserPollOptionVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Placement")
                        .HasColumnType("int");

                    b.Property<int>("PollOptionFK")
                        .HasColumnType("int");

                    b.Property<int>("UserFK")
                        .HasColumnType("int");

                    b.Property<string>("WriteInText")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PollOptionFK");

                    b.HasIndex("UserFK", "PollOptionFK")
                        .IsUnique();

                    b.ToTable("UserPollOptionVote");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.UserRight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Right")
                        .HasColumnType("int");

                    b.Property<int>("UserFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserFK");

                    b.ToTable("UserRight");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.Webhook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBySteamId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Event")
                        .HasColumnType("int");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Event");

                    b.ToTable("Webhook");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.BasicPoll", b =>
                {
                    b.HasBaseType("WolflineSquadTTT.Models.Poll");

                    b.HasDiscriminator().HasValue("BasicPoll");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.MultiSelectPoll", b =>
                {
                    b.HasBaseType("WolflineSquadTTT.Models.Poll");

                    b.Property<int?>("MaxSelections")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("MultiSelectPoll");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.RankingPoll", b =>
                {
                    b.HasBaseType("WolflineSquadTTT.Models.Poll");

                    b.HasDiscriminator().HasValue("RankingPoll");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.Poll", b =>
                {
                    b.HasOne("WolflineSquadTTT.Models.Reward", "Reward")
                        .WithMany()
                        .HasForeignKey("RewardFK");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.PollOption", b =>
                {
                    b.HasOne("WolflineSquadTTT.Models.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.RewardClaim", b =>
                {
                    b.HasOne("WolflineSquadTTT.Models.Poll", "Poll")
                        .WithMany()
                        .HasForeignKey("PollFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WolflineSquadTTT.Models.Reward", "Reward")
                        .WithMany()
                        .HasForeignKey("RewardFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WolflineSquadTTT.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");

                    b.Navigation("Reward");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.UserPollOptionVote", b =>
                {
                    b.HasOne("WolflineSquadTTT.Models.PollOption", "PollOption")
                        .WithMany()
                        .HasForeignKey("PollOptionFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WolflineSquadTTT.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PollOption");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.UserRight", b =>
                {
                    b.HasOne("WolflineSquadTTT.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WolflineSquadTTT.Models.Poll", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
